-- ==========================
-- SEQUENCES
-- ==========================
CREATE SEQUENCE SEQ_CARGO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PROFISSIONAL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PROFISSIONAL_CARGO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IMOBILIARIA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONFIG_COMISSAO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VENDA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PARCELA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_COMISSAO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_USER START WITH 1 INCREMENT BY 1;

-- ==========================
-- TABELAS
-- ==========================
CREATE TABLE CARGO (
    id INT PRIMARY KEY DEFAULT nextval('SEQ_CARGO'),
    nome VARCHAR(255)
);

CREATE TABLE PROFISSIONAL (
    id INT PRIMARY KEY DEFAULT nextval('SEQ_PROFISSIONAL'),
    nome VARCHAR(255)
);

CREATE TABLE PROFISSIONAL_CARGO (
    id INT PRIMARY KEY DEFAULT nextval('SEQ_PROFISSIONAL_CARGO'),
    id_profissional INT REFERENCES PROFISSIONAL(id),
    id_cargo INT REFERENCES CARGO(id)
);

CREATE TABLE IMOBILIARIA (
    id INT PRIMARY KEY DEFAULT nextval('SEQ_IMOBILIARIA'),
    nome VARCHAR(255),
    meta NUMERIC(19,2)
);

CREATE TABLE CONFIG_COMISSAO (
    id INT PRIMARY KEY DEFAULT nextval('SEQ_CONFIG_COMISSAO'),
    percentual NUMERIC(19,2),
    id_imobiliaria INT REFERENCES IMOBILIARIA(id),
    id_cargo INT REFERENCES CARGO(id)
);

CREATE TABLE VENDA (
    id INT PRIMARY KEY DEFAULT nextval('SEQ_VENDA'),
    descricao_imovel VARCHAR(255),
    valor_total NUMERIC(19,2),
    data_venda TIMESTAMP,
    forma_pagamento VARCHAR(50),
    qtd_parcelas INT,
    comprador_nome VARCHAR(255),
    comprador_contato VARCHAR(255)
);

CREATE TABLE PARCELA (
    id INT PRIMARY KEY DEFAULT nextval('SEQ_PARCELA'),
    numero_parcela INT,
    valor_parcela NUMERIC(19,2),
    data_vencimento TIMESTAMP,
    status VARCHAR(50),
    id_venda INT REFERENCES VENDA(id)
);

CREATE TABLE COMISSAO (
    id INT PRIMARY KEY DEFAULT nextval('SEQ_COMISSAO'),
    percentual NUMERIC(19,2),
    valor_comissao NUMERIC(19,2),
    id_venda INT REFERENCES VENDA(id),
    id_profissional INT REFERENCES PROFISSIONAL(id)
);

CREATE TABLE USERS (
    id INT PRIMARY KEY DEFAULT nextval('SEQ_USER'),
    nome VARCHAR(255),
    email VARCHAR(255),
    senha VARCHAR(255),
    role VARCHAR(50)
);
